//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.19.0
//     from Assets/StorytellersTable/InputSettings/CampaignMode/MapEditAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/StorytellersTable/InputSettings/CampaignMode/MapEditAction.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @MapEditAction: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @MapEditAction()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""MapEditAction"",
    ""maps"": [
        {
            ""name"": ""Edit"",
            ""id"": ""b5ecaa16-b0a3-4ad1-94d2-0b269acbc76e"",
            ""actions"": [
                {
                    ""name"": ""Toggle Single"",
                    ""type"": ""Button"",
                    ""id"": ""4202358f-a3aa-47e4-8ea8-80fad3bf31af"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Toggle Radial"",
                    ""type"": ""Button"",
                    ""id"": ""4541399f-02e6-4004-9289-3a37b8187f3a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Toggle Area"",
                    ""type"": ""Button"",
                    ""id"": ""c043a19c-997f-444f-be1c-4c0a60a1c700"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Toggle Draw"",
                    ""type"": ""Button"",
                    ""id"": ""c95e7bd3-1b96-4ae6-83fa-8f5b9750017d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Clear Selection"",
                    ""type"": ""Button"",
                    ""id"": ""a3a19e78-85e8-456c-bb5a-6ad70ab2cbe3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Toggle Tile Remove"",
                    ""type"": ""Button"",
                    ""id"": ""adc0d0ce-aa49-475c-aabc-ff6e5f2e525a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""32c0a76a-82ca-4cf7-8ef0-f12ecb1ebd91"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Toggle Radial"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b90df6dd-a319-4cc1-8662-8098ef633345"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Toggle Area"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""57e721c1-2a5e-45c4-ad09-45f3d4eabcbf"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Toggle Draw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d96643f7-f9eb-46e6-909d-fcc66eee7029"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Toggle Single"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6a6237a2-be9b-4b7d-a944-f3329e39da5a"",
                    ""path"": ""<Keyboard>/backquote"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Clear Selection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7f3eb222-401d-46aa-9df7-ed81d560d3a1"",
                    ""path"": ""<Keyboard>/minus"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Toggle Tile Remove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Edit
        m_Edit = asset.FindActionMap("Edit", throwIfNotFound: true);
        m_Edit_ToggleSingle = m_Edit.FindAction("Toggle Single", throwIfNotFound: true);
        m_Edit_ToggleRadial = m_Edit.FindAction("Toggle Radial", throwIfNotFound: true);
        m_Edit_ToggleArea = m_Edit.FindAction("Toggle Area", throwIfNotFound: true);
        m_Edit_ToggleDraw = m_Edit.FindAction("Toggle Draw", throwIfNotFound: true);
        m_Edit_ClearSelection = m_Edit.FindAction("Clear Selection", throwIfNotFound: true);
        m_Edit_ToggleTileRemove = m_Edit.FindAction("Toggle Tile Remove", throwIfNotFound: true);
    }

    ~@MapEditAction()
    {
        UnityEngine.Debug.Assert(!m_Edit.enabled, "This will cause a leak and performance issues, MapEditAction.Edit.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Edit
    private readonly InputActionMap m_Edit;
    private List<IEditActions> m_EditActionsCallbackInterfaces = new List<IEditActions>();
    private readonly InputAction m_Edit_ToggleSingle;
    private readonly InputAction m_Edit_ToggleRadial;
    private readonly InputAction m_Edit_ToggleArea;
    private readonly InputAction m_Edit_ToggleDraw;
    private readonly InputAction m_Edit_ClearSelection;
    private readonly InputAction m_Edit_ToggleTileRemove;
    /// <summary>
    /// Provides access to input actions defined in input action map "Edit".
    /// </summary>
    public struct EditActions
    {
        private @MapEditAction m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public EditActions(@MapEditAction wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Edit/ToggleSingle".
        /// </summary>
        public InputAction @ToggleSingle => m_Wrapper.m_Edit_ToggleSingle;
        /// <summary>
        /// Provides access to the underlying input action "Edit/ToggleRadial".
        /// </summary>
        public InputAction @ToggleRadial => m_Wrapper.m_Edit_ToggleRadial;
        /// <summary>
        /// Provides access to the underlying input action "Edit/ToggleArea".
        /// </summary>
        public InputAction @ToggleArea => m_Wrapper.m_Edit_ToggleArea;
        /// <summary>
        /// Provides access to the underlying input action "Edit/ToggleDraw".
        /// </summary>
        public InputAction @ToggleDraw => m_Wrapper.m_Edit_ToggleDraw;
        /// <summary>
        /// Provides access to the underlying input action "Edit/ClearSelection".
        /// </summary>
        public InputAction @ClearSelection => m_Wrapper.m_Edit_ClearSelection;
        /// <summary>
        /// Provides access to the underlying input action "Edit/ToggleTileRemove".
        /// </summary>
        public InputAction @ToggleTileRemove => m_Wrapper.m_Edit_ToggleTileRemove;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Edit; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="EditActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(EditActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="EditActions" />
        public void AddCallbacks(IEditActions instance)
        {
            if (instance == null || m_Wrapper.m_EditActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_EditActionsCallbackInterfaces.Add(instance);
            @ToggleSingle.started += instance.OnToggleSingle;
            @ToggleSingle.performed += instance.OnToggleSingle;
            @ToggleSingle.canceled += instance.OnToggleSingle;
            @ToggleRadial.started += instance.OnToggleRadial;
            @ToggleRadial.performed += instance.OnToggleRadial;
            @ToggleRadial.canceled += instance.OnToggleRadial;
            @ToggleArea.started += instance.OnToggleArea;
            @ToggleArea.performed += instance.OnToggleArea;
            @ToggleArea.canceled += instance.OnToggleArea;
            @ToggleDraw.started += instance.OnToggleDraw;
            @ToggleDraw.performed += instance.OnToggleDraw;
            @ToggleDraw.canceled += instance.OnToggleDraw;
            @ClearSelection.started += instance.OnClearSelection;
            @ClearSelection.performed += instance.OnClearSelection;
            @ClearSelection.canceled += instance.OnClearSelection;
            @ToggleTileRemove.started += instance.OnToggleTileRemove;
            @ToggleTileRemove.performed += instance.OnToggleTileRemove;
            @ToggleTileRemove.canceled += instance.OnToggleTileRemove;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="EditActions" />
        private void UnregisterCallbacks(IEditActions instance)
        {
            @ToggleSingle.started -= instance.OnToggleSingle;
            @ToggleSingle.performed -= instance.OnToggleSingle;
            @ToggleSingle.canceled -= instance.OnToggleSingle;
            @ToggleRadial.started -= instance.OnToggleRadial;
            @ToggleRadial.performed -= instance.OnToggleRadial;
            @ToggleRadial.canceled -= instance.OnToggleRadial;
            @ToggleArea.started -= instance.OnToggleArea;
            @ToggleArea.performed -= instance.OnToggleArea;
            @ToggleArea.canceled -= instance.OnToggleArea;
            @ToggleDraw.started -= instance.OnToggleDraw;
            @ToggleDraw.performed -= instance.OnToggleDraw;
            @ToggleDraw.canceled -= instance.OnToggleDraw;
            @ClearSelection.started -= instance.OnClearSelection;
            @ClearSelection.performed -= instance.OnClearSelection;
            @ClearSelection.canceled -= instance.OnClearSelection;
            @ToggleTileRemove.started -= instance.OnToggleTileRemove;
            @ToggleTileRemove.performed -= instance.OnToggleTileRemove;
            @ToggleTileRemove.canceled -= instance.OnToggleTileRemove;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="EditActions.UnregisterCallbacks(IEditActions)" />.
        /// </summary>
        /// <seealso cref="EditActions.UnregisterCallbacks(IEditActions)" />
        public void RemoveCallbacks(IEditActions instance)
        {
            if (m_Wrapper.m_EditActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="EditActions.AddCallbacks(IEditActions)" />
        /// <seealso cref="EditActions.RemoveCallbacks(IEditActions)" />
        /// <seealso cref="EditActions.UnregisterCallbacks(IEditActions)" />
        public void SetCallbacks(IEditActions instance)
        {
            foreach (var item in m_Wrapper.m_EditActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_EditActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="EditActions" /> instance referencing this action map.
    /// </summary>
    public EditActions @Edit => new EditActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Edit" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="EditActions.AddCallbacks(IEditActions)" />
    /// <seealso cref="EditActions.RemoveCallbacks(IEditActions)" />
    public interface IEditActions
    {
        /// <summary>
        /// Method invoked when associated input action "Toggle Single" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnToggleSingle(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Toggle Radial" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnToggleRadial(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Toggle Area" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnToggleArea(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Toggle Draw" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnToggleDraw(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Clear Selection" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnClearSelection(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Toggle Tile Remove" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnToggleTileRemove(InputAction.CallbackContext context);
    }
}
